-- Harvest Tool Training — STARTER CONTENT (lesson text + test questions), authored to
-- draft so the office has a full training to review and EDIT on the Training admin page.
-- Run AFTER sql/harvest_training.sql. Safe to re-run: it only fills sections whose body
-- is still blank, and only seeds questions if a track has none yet — so your edits and
-- uploaded screenshots are never clobbered.

-- ── REP lesson bodies (only fill blanks) ────────────────────────────────────
update public.harvest_training_sections set body = $q$Read each section below, then take a short test. Score 80% or higher and your map unlocks. Miss too many and you'll come back here to re-read the sections you got wrong before you retake it. It only takes a few minutes and makes your day in the field way easier.$q$
  where track='rep' and title='Welcome — how this works' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Your map opens to your area. Every dot is a door, and its COLOR tells you what kind of door it is — IQ leads, Inspection Leads, Appointments, No-sits, and so on. The legend on the right lists every type with a count. Doors already worked today keep their real status color, and the map won't route you back to a door someone already worked today. Gold stars are roofs we've already installed — a reference only, not doors to knock. Tap any pin to see the homeowner's info.$q$
  where track='rep' and title='Opening your map & reading the pins' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Tap ▶ Start my day, then choose where you're starting — "from my location" (GPS) or tap the map to set a spot. The map builds the most efficient route through your nearest doors and walks you one stop at a time, with a Directions button to each. You can only log a door once you're actually AT it (your GPS has to say you're within range) — that keeps everyone honest. When you're there, the "How'd it go?" buttons light up.$q$
  where track='rep' and title='Start my day' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Want to work one specific neighborhood? Tap ▢ Route an area and drag a box around the doors you want. It routes exactly those, in an efficient order. This works even when you're zoomed way out — you don't have to zoom in first.$q$
  where track='rep' and title='Route an area' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$If you have appointments today, tap "📅 Have an appt? Plan your day!" Enter what time you're starting (your day ends at 8 PM). It drops your appointments in, in order, and fills the gaps before, between, and after them with doors — sized by the clock so you're never late for an appointment. When you leave an appointment, tap "✅ Appointment done" and it re-plans the rest around the real time (finish early = more doors, run long = fewer). It also routes you back toward where you started by the end of the day.$q$
  where track='rep' and title='Plan your day around your appointments' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$When you're at a door (the buttons unlock when your GPS says you're there), tap what happened — Not home, Not interested, booked an appointment, and so on. It logs it and moves you to the next stop automatically. If your GPS is weak and you're really at the door, use the "I'm at the door" button — but know that WHERE you were when you logged it is recorded. Never log doors you aren't actually standing at.$q$
  where track='rep' and title='Statusing a door (how''d it go?)' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$After an inspection, some homeowners need a follow-up visit — a "go-back." Those show up as dated pins and in the "go-backs to work" card. When you're building a route, tap "Add the go-backs within my route" and it folds in only the ones near where you're already working, not ones across the county.$q$
  where track='rep' and title='Go-backs' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Standing with a homeowner who's ready to move forward? Tap "🖊️ Sign Inspection" on that door. It opens the claim intake already filled in with what we know about them. Finish it, and once they sign, the door is marked Inspection Sold and you move on to your next stop.$q$
  where track='rep' and title='Sign an inspection' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Spot a damaged roof that isn't on your map? Drop your own pin on it. The map checks whether it's owner-occupied, and if so lets you sign it, book a retail appointment, or mark it pending. It goes into JobNimbus as a Self-Generated lead so you get the credit.$q$
  where track='rep' and title='Drop your own pin (self-generated lead)' and coalesce(body,'')='';

-- ── MANAGER lesson bodies (only fill blanks) ────────────────────────────────
update public.harvest_training_sections set body = $q$You'll read each section, then take a short test. Score 80% or higher to unlock your tools. Miss too many and you'll come back to re-read the sections you got wrong before retaking. This covers the whole Harvesting system so you can coach your team on it.$q$
  where track='manager' and title='Welcome — how this certification works' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$The Harvesting Map is where your reps knock doors. Leads get loaded onto it, reps work them on efficient routes, and every knock and outcome is logged automatically. As a manager you oversee how your team uses it — so this training walks through the whole system, including the tools your reps touch.$q$
  where track='manager' and title='The Harvesting Map — the big picture' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$On your dashboard, open the "🗺️ Live Team Map." It shows ONLY your zone's reps: where each one is right now (a live dot + a breadcrumb trail of where they've been), who's live vs. idle, and each rep's counts for the day — knocks, signed, appointments. It refreshes every 30 seconds. A rep drops to "idle" after ~15 minutes with no GPS ping, or right away when they close their map. If a rep is missing, they're usually not zoned to you or haven't started working yet.$q$
  where track='manager' and title='Your Live Team Map (where your reps are)' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Reps with appointments can tap "Plan your day." It orders their appointments and fills the gaps before, between, and after with doors — sized by the clock so they're never late — and routes them back toward where they started by 8 PM. When a rep leaves an appointment they tap "Appointment done" and it re-plans the rest around the real time. Encourage reps to use it on appointment days.$q$
  where track='manager' and title='How your reps plan their day (Smart Scheduling)' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Reps have two ways to route: "Start my day" builds an efficient route from their location, and "Route an area" lets them draw a box around a specific neighborhood. Either way, a rep can only log a door when their GPS shows they're actually there — that's the honesty gate.$q$
  where track='manager' and title='Start my day & Route an area' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$After an inspection, homeowners who need a follow-up show up as "go-backs" — dated pins the rep can fold into their route. Keep an eye on the go-back list so follow-ups don't age out and get lost.$q$
  where track='manager' and title='Go-backs' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$When a homeowner is ready, the rep taps "Sign Inspection," which opens the pre-filled claim intake. Once the homeowner signs, the door is marked Inspection Sold — and it shows up on your deal board.$q$
  where track='manager' and title='Signing an inspection' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$Every status a rep logs records WHERE they were and how far they were from the door. A rep sitting at home tapping "not home" to fake work stands out: statuses logged far from the door, or a pile of them logged from one spot. Watch the report's "Off-spot" column and the 🚩 flag banner — it points you to reps worth a closer look.$q$
  where track='manager' and title='Location audit — spotting fake work' and coalesce(body,'')='';
update public.harvest_training_sections set body = $q$The activity report (per rep) shows pins visited, outcomes (appointments, sold, not-interested), time at each door, and the location flags. Use it to see who's really out working hard and who needs coaching.$q$
  where track='manager' and title='Reading the reports' and coalesce(body,'')='';

-- ── REP questions (only if none exist yet) ──────────────────────────────────
do $do$
begin
  if not exists (select 1 from public.harvest_training_questions where track='rep') then
    insert into public.harvest_training_questions (track, section_id, sort, prompt, choices, correct_index) values
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Opening your map & reading the pins' limit 1), 10, $q$What does a pin's COLOR on your map tell you?$q$, jsonb_build_array($q$The homeowner's name$q$, $q$What kind of door it is (its status)$q$, $q$How far away it is$q$, $q$Nothing$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Start my day' limit 1), 20, $q$When can you log what happened at a door?$q$, jsonb_build_array($q$Any time, from anywhere$q$, $q$Only when your GPS shows you're at the door$q$, $q$Only in the morning$q$, $q$After you leave the neighborhood$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Start my day' limit 1), 30, $q$How do you begin a route through your nearest doors?$q$, jsonb_build_array($q$Tap ▶ Start my day and pick where you're starting$q$, $q$Call the office$q$, $q$Refresh the page$q$, $q$You can't$q$), 0),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Route an area' limit 1), 40, $q$You want to work one specific neighborhood. What do you do?$q$, jsonb_build_array($q$Drive there and guess$q$, $q$Tap ▢ Route an area and draw a box around it$q$, $q$You must zoom all the way in first$q$, $q$Nothing$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Plan your day around your appointments' limit 1), 50, $q$You have two appointments today. What does "Plan your day" do?$q$, jsonb_build_array($q$Cancels your appointments$q$, $q$Puts your appointments in order and fills the gaps with doors so you're never late$q$, $q$Only shows the appointments$q$, $q$Sends you home$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Plan your day around your appointments' limit 1), 60, $q$You just left an appointment. What should you tap?$q$, jsonb_build_array($q$Start over$q$, $q$✅ Appointment done, so it re-plans the rest of your day$q$, $q$Nothing$q$, $q$Cancel route$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Statusing a door (how''d it go?)' limit 1), 70, $q$Your GPS is weak but you're really at the door. What's true?$q$, jsonb_build_array($q$You can log doors from home, it's fine$q$, $q$You can log it, but where you were is recorded — so only log doors you're actually at$q$, $q$You can never log it$q$, $q$It logs the door as sold$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Go-backs' limit 1), 80, $q$What does "Add the go-backs within my route" do?$q$, jsonb_build_array($q$Adds every go-back in the whole county$q$, $q$Adds only the go-backs near where you're already working$q$, $q$Deletes your go-backs$q$, $q$Nothing$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Sign an inspection' limit 1), 90, $q$A homeowner is ready to sign. What do you tap on their door?$q$, jsonb_build_array($q$Not home$q$, $q$🖊️ Sign Inspection, which opens the pre-filled intake$q$, $q$Start my day$q$, $q$Delete pin$q$), 1),
    ('rep', (select id from public.harvest_training_sections where track='rep' and title='Drop your own pin (self-generated lead)' limit 1), 100, $q$You spot a damaged roof that isn't on your map. What can you do?$q$, jsonb_build_array($q$Ignore it$q$, $q$Drop your own pin on it — it becomes a Self-Generated lead you get credit for$q$, $q$Only tell the office by phone$q$, $q$Nothing$q$), 1);
  end if;
end $do$;

-- ── MANAGER questions (only if none exist yet) ──────────────────────────────
do $do$
begin
  if not exists (select 1 from public.harvest_training_questions where track='manager') then
    insert into public.harvest_training_questions (track, section_id, sort, prompt, choices, correct_index) values
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='The Harvesting Map — the big picture' limit 1), 10, $q$What is the Harvesting Map for?$q$, jsonb_build_array($q$Payroll$q$, $q$Where reps knock doors and every knock/outcome is logged$q$, $q$Scheduling meetings$q$, $q$Nothing$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Your Live Team Map (where your reps are)' limit 1), 20, $q$The Live Team Map on your dashboard shows…$q$, jsonb_build_array($q$Every rep in the company$q$, $q$Only YOUR zone's reps$q$, $q$Just a static list$q$, $q$The homeowners$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Your Live Team Map (where your reps are)' limit 1), 30, $q$How often does the Live Team Map refresh?$q$, jsonb_build_array($q$Once a day$q$, $q$Every 30 seconds$q$, $q$Never$q$, $q$Only when you click$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Your Live Team Map (where your reps are)' limit 1), 40, $q$When does a rep show as "idle" on the map?$q$, jsonb_build_array($q$Always$q$, $q$After ~15 min with no GPS ping, or when they close their map$q$, $q$Never$q$, $q$Only at 8 PM$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Your Live Team Map (where your reps are)' limit 1), 50, $q$A rep is missing from your Live Team Map. A likely reason is…$q$, jsonb_build_array($q$The map is broken$q$, $q$They're not zoned to you, or haven't started working today$q$, $q$They quit$q$, $q$The internet is down$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='How your reps plan their day (Smart Scheduling)' limit 1), 60, $q$What does "Plan your day" do for a rep with appointments?$q$, jsonb_build_array($q$Cancels them$q$, $q$Orders the appointments and fills the gaps with doors so they're never late$q$, $q$Only shows the appointments$q$, $q$Sends them home$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='How your reps plan their day (Smart Scheduling)' limit 1), 70, $q$A rep leaves an appointment early. What should they tap so the plan adjusts?$q$, jsonb_build_array($q$Start over$q$, $q$Appointment done$q$, $q$Nothing$q$, $q$Cancel$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='How your reps plan their day (Smart Scheduling)' limit 1), 80, $q$By the end of the day, "Plan your day" routes the rep…$q$, jsonb_build_array($q$To a random spot$q$, $q$Back toward where they started, done by 8 PM$q$, $q$Out of state$q$, $q$Nowhere$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Start my day & Route an area' limit 1), 90, $q$How can a rep route one specific neighborhood?$q$, jsonb_build_array($q$Guess$q$, $q$Route an area — draw a box around it$q$, $q$Call you$q$, $q$They can't$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Start my day & Route an area' limit 1), 100, $q$When can a rep log what happened at a door?$q$, jsonb_build_array($q$Anywhere, any time$q$, $q$When their GPS shows they're at the door$q$, $q$Only from home$q$, $q$Never$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Go-backs' limit 1), 110, $q$What are go-backs?$q$, jsonb_build_array($q$Deleted leads$q$, $q$Homeowners who need a follow-up visit after an inspection$q$, $q$Appointments$q$, $q$Installed roofs$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Signing an inspection' limit 1), 120, $q$When a homeowner signs, the door is marked…$q$, jsonb_build_array($q$Not home$q$, $q$Inspection Sold$q$, $q$Dead$q$, $q$Nothing$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Location audit — spotting fake work' limit 1), 130, $q$Every status a rep logs records…$q$, jsonb_build_array($q$Nothing$q$, $q$Where they were and how far from the door$q$, $q$Only the time$q$, $q$The weather$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Location audit — spotting fake work' limit 1), 140, $q$How would you spot a rep faking "not home" from their couch?$q$, jsonb_build_array($q$You can't$q$, $q$The report flags statuses logged far from the door, or a pile from one spot$q$, $q$Only by calling them$q$, $q$It's impossible$q$), 1),
    ('manager', (select id from public.harvest_training_sections where track='manager' and title='Reading the reports' limit 1), 150, $q$Where do you see who's really out working vs. who needs coaching?$q$, jsonb_build_array($q$The activity report$q$, $q$JobNimbus only$q$, $q$Nowhere$q$, $q$Ask the homeowner$q$), 0);
  end if;
end $do$;
